FileVersion = 1

[Project]
Name = "libcsv-beef"
TargetType = "BeefLib"
StartupObject = "libcsv_beef.Program"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\libcsv_d.lib"]
