FileVersion = 1

[Project]
Name = "libcsv-beef"
DefaultNamespace = "libcsv"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\libcsv_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\libcsv.lib"]